# Generated by Django 4.2.5 on 2023-10-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_alter_gallery_donation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='donor',
            new_name='Donor',
        ),
    ]
