# Generated by Django 4.2.5 on 2023-10-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_rename_donor_donation_donor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='Donor',
            new_name='donor',
        ),
    ]
