# Generated by Django 4.2.5 on 2023-10-06 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_alter_donation_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donationarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donation.donationarea'),
        ),
    ]
